---
abstract: 'Provides support for loading 3D models from RWX files'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.80
  Test::NoWarnings: 1.00
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: OpenGL::RWX
name: OpenGL-RWX
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Spec: 3.31
  IO::File: 1.14
  OpenGL: 0.64
  OpenGL::List: 0.01
  perl: 5.8.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/OpenGL-RWX
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/OpenGL-RWX
version: 0.01
